### ISSUE TITLE
Could you add more details on data preparation?

### ISSUE THREAD

**Issue by mahesh-kumar-nlp** [microsoft/MetaXL#2]
I could see that the training code is looking for some file which is in json format. Could you provide details with respect to the structure in which the data has to be sent and if possible a example.

**Comment by xiamengzhou** [comment]
Hi, due to intellectual property issues, we can't put actual data examples in the code repo. The structure of the JSON files is as follows: {"review_body": "", "language": "", "label": ""}

**Comment by mahesh-kumar-nlp** [comment]
Thanks you so much for the response. Will try this out.
