### ISSUE TITLE
Sentiment Classification - Clarification

### ISSUE THREAD

**Issue by ashissamal** [microsoft/MetaXL#3]
Thank you team for sharing the wonderful approach and repo. While experimenting the existing implementation for sentiment analysis meta learning for `en` and `te` languages, I came across the `SequenceTagger` object which inherits `XLMRobertaForTokenClassification` class. As per my understanding, it should be `XLMRobertaForSequenceClassification` for text classifications like Sentiment, Intent. Where as `XLMRobertaForTokenClassification`, would be apt for NER use cases. 

Please correct me if I am misunderstood.

**Comment by xiamengzhou** [comment]
Hi, sorry for the confusion. Yeah you are right, we should have used XLMRobertaForSequenceClassification for sentiment analysis. But at the time, we simply build the sequence classification module on top of the XLMRobertaForTokenClassification module by adding a flag and an additional classifier. It's essentially the same as XLMRobertaForSequenceClassification. Please let me know if you have more questions!

**Comment by ashissamal** [comment]
Thank you for the clarification.
